### PR TITLE
Feature/misc fixes

### PR DESCRIPTION
**Pull request by Hdom**

### CODE REVIEW

**Comment by gabriel-samfira** [comment]
Hi @Hdom !

Generally it's a good idea to add a description to the pull request, briefly describing the fix, even if the title contains most of the relevant info.

A cool trick that github allows is to add in the description something like:

Fixes #7
Fixes #8 

And when the PR gets merged, the issues are automatically closed.

I will have a look at the changes later today and post a review or just merge.

Thanks for the PR!

**Review by gabriel-samfira — APPROVED** [review]

**Comment by gabriel-samfira** [comment]
Thanks for the fixes!

**Comment by Hdom** [comment]
> Hi @Hdom !
> 
> Generally it's a good idea to add a description to the pull request, briefly describing the fix, even if the title contains most of the relevant info.
> 
> A cool trick that github allows is to add in the description something like:
> 
> Fixes #7 Fixes #8
> 
> And when the PR gets merged, the issues are automatically closed.
> 
> I will have a look at the changes later today and post a review or just merge.
> 
> Thanks for the PR!

My bad, it was late and I wanted to create the PR before going to sleep, was expecting it to grab the commit messages and use them as description, usually it does that but I've never done a cross repo PR like this before. Next time I'll make sure to provide proper description, hopefully everything was well understood.

**Comment by gabriel-samfira** [comment]
Yup. The issues you opened were okay and the PR was clear. Cross linking is usually done between issues and PRs, rarely commits as thise can be squashed or replaced via force push.

But no worries either way. Its more of a good etiquette thing for future developers trying to figure out when a change occured and why by going through the least amount of clicks 😁

**Pull request merged**
